version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vibranium
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - vibranium_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - vibranium_network

  orderbookmanager:
    image: orderbookmanager
    build:
      context: /orderbookmanager
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - /orderbookmanager/target/*.jar orderbookmanager.jar
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - vibranium_network

  trademanager:
    image: trademanager
    build:
      context: /trademanager
      dockerfile: Dockerfile
    ports:
      - "9091:9091"
    volumes:
      - /trademanager/target/*.jar trademanager.jar
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - vibranium_network

  vibraniumapi:
    image: vibraniumapi
    build:
      context: /vibraniumapi
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /users/target/*.jar vibraniumapi.jar
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - vibranium_network


networks:
  vibranium_network:
    driver: bridge
