global:
  scrape_interval: 30s
  scrape_timeout: 25s

scrape_configs:
  - job_name: 'api-vibranium-job'
    metrics_path: "/vibranium/actuator/prometheus"
    static_configs:
      - targets: ['localhost:8080']
        labels:
          application: "api-vibranium"
